codecov:
  token: "ba961ca1-57a7-4a22-ad2e-5819eea559da"
ignore:
  - "Example"  # ignore demo
  - "GrowingTrackerCore/NetWork" # ignore network ,websocket
  - "GrowingTrackerCore/Thirdparty"  # ignore Thirdparty
  - "Modules/Protobuf/Proto"
  - "Services/Compression/LZ4"
  - "Services/Database/FMDB"
  - "Services/WebSocket"

